/***********************************************************************/
/*                                                                     */
/*  FILE        :Empty.c                                               */
/*  DATE        :Mon, Jan 08, 2007                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
     
#include "qsk_bsp.h"
#include "qsk_lcd.h"

// prototypes

void mcu_init(void);	              

/* *******************************************************************
 Description:
 Entry:
 Returns:
 
 Notes:
 
***********************************************************************/ 
void main(void)
{
	
	mcu_init();
	
	InitDisplay();
	
	DisplayString(LCD_LINE1, "abcdefghijklmnopqrstu");
	
	DisplayCursorOn();
	DisplayCursorBlinkOn();
	
	while(1) {
		DisplayDelay(1000);
		DisplayCursorLeftMove();
	}
	
}
